#!/bin/bash
goalip=$1
for ((i=1;i>0;i++)); do 
	ip=$( ifconfig wlan0 | grep inet | head -c26 | tail -c13 )
	if [ "$ip" != $goalip ]; then 
		killall dhcpcd
		rm -f /run/dhcpcd-wlp2s0.pid
		dhcpcd wlp2s0
		sleep 15
	else
		echo -ne "\r""Net UP-"$i
		sleep 3
	fi
done

