#!/bin/bash
goalip=$1
device=$2
for ((i=1;i>0;i++)); do 
	ip=$( ifconfig $device | grep inet | head -c26 | tail -c13 )
	if [ "$ip" != $goalip ]; then 
		killall dhcpcd
		rm -f "/run/dhcpcd-$device.pid"
		dhcpcd $device
		sleep 15
	else
		echo -ne "\r""Net UP-"$i
		sleep 3
	fi
done

