#!/bin/bash
function check_root {
checkuser=( $(whoami) )
if [ "$checkuser" != "root" ]; then
echo "Must run update as root!!"
exit
fi
}

function check_user {
checkuser=( $(whoami) )
if [ "$checkuser" = "root" ]; then
echo "Please do searches as normal user."
exit
fi
}

function prep_setup {
echo Doing Setup...
tmp_prefix="/gen-portage-list"
port_prefix="/usr/portage"
rm -rf $tmp_prefix
mkdir $tmp_prefix
full_layer=($( ls $port_prefix | grep -v distfiles | grep -v licenses | grep -v profiles | grep -v scripts |
grep -v eclass | grep -v packages | grep -v metadata | grep -v skel | grep -v header.txt))
echo Done.
}

function indexer {
echo Starting Index Creation...
echo "DON'T TOUCH ANYTHING UNTIL THIS IS DONE!!"
echo "WAIT FOR PROMPT!! IT ONLY TAKES ABOUT"
echo "5 MINUTES ON A SLOW SYSTEM."
for ((i=0; i<${#full_layer[@]}; i++)); do
	prog=$(( $prog + 1 ))
	pkg_list=( $( ls $port_prefix/${full_layer[$i]} | grep -v metadata ) )
	for ((j=0; j<${#pkg_list[@]}; j++)); do
		ebuild_ary[$j]="${full_layer[$i]}/"
		ebuild_file=$(ls "$port_prefix/${full_layer[$i]}/${pkg_list[$j]}" | grep ebuild | head -n1)
		ebuild_ary[$j]="$ebuild_file "
		ebuild_ary[$j]+=$(grep DESCRIPTION $port_prefix/${full_layer[$i]}/${pkg_list[$j]}/${ebuild_ary[$j]})
	done
	printf -- '%s\n' "${ebuild_ary[@]}" > $tmp_prefix/${full_layer[$i]}.index
done
}

function install_clean {
echo "Enter username for final priv adjustment:"
read user
echo Installing...
rm -rf /home/$user/scriptkit/extras/port-find-index
mkdir /home/$user/scriptkit/extras/port-find-index
mv $tmp_prefix/*.index /home/$user/scriptkit/extras/port-find-index
chown -R $user:users /home/$user/scriptkit/extras
index_list=( $(ls /home/$user/scriptkit/extras/port-find-index) )
for (( i=0; i<"${#index_list[@]}"; i++ )); do
	awk '!a[$0]++' /home/$user/scriptkit/extras/port-find-index/${index_list[$i]} > /home/$user/scriptkit/extras/port-find-index/desc-${index_list[$i]}.index
	rm -f /home/$user/scriptkit/extras/port-find-index/desc-${index_list[$i]}.index
done
rm -rf "$tmp_prefix"
}

function updater {
prep_setup
indexer
install_clean
}

if [ "$1" = "update" ]; then
	check_root
	echo Updating File Database...
	updatedb -e /mnt -e /media -e /run
	updater
else
	check_user
	index_ary=( $(ls ${HOME}/scriptkit/extras/port-find-index) )
	for (( i=0; i<${#index_ary[@]}; i++ )); do
		cat ${HOME}/scriptkit/extras/port-find-index/${index_ary[$i]} | grep $1
	done
fi
